blog/urls.py
#!/usr/bin/evn python
# -*- coding:utf-8 -*-
# @Date    : 2019-07-22
# @Author  : suxianglun
# @Describe :
# @Version :
from django.conf.urls import url, include

from blog import views
app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='home'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    url(r'^course_list/$', views.CourseListView.as_view(), name='course_list'),
    url(r'^course/(?P<pk>[0-9]+)/$', views.CourseView.as_view(), name='course'),
]

blog/models.py
from django.db import models
from datetime import datetime

# Create your models here.
from django.utils.six import python_2_unicode_compatible
from django.conf import settings
from django.utils.six import python_2_unicode_compatible
from django.urls import reverse
from django.utils.html import strip_tags

from stdimage.models import StdImageField
from stdimage.utils import UploadToUUID

import markdown
import mistune

import pdb


class Course(models.Model):
    """
    教程
    """
    name = models.CharField(verbose_name='名称', max_length=30)
    # 配图
    image = StdImageField(verbose_name='配图', blank=True,
                          upload_to=UploadToUUID(path='images'),  # 上传路径并使用uuid重新命名 MEDIA_ROOT/images/#UUID#.#EXT#
                          variations={'thumbnail': {"width": 200, "height": 200, "crop": True}})  # 缩略图

    # 图片已经上传情况下，直接使用img_url
    img_url = models.URLField(verbose_name='外部图片url', blank=True, null=True)

    @python_2_unicode_compatible
    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = verbose_name = '教程'

    def url(self):
        """
        获取img_url
        :return:
        """
        if self.image:
            return self.image.url
        else:
            return ""

    def image_img(self):
        if self.image:
            href = self.image.url  # 点击后显示的放大图片
            src = self.image.thumbnail.url  # 页面显示的缩略图
            # 插入html代码
            image_html = '<a href="%s" target="_blank" title="图片下载地址"><img alt="" src="%s"/>' % (href, src)
            return image_html
        else:
            return ''

    image_img.short_description = '显示图片'  # 显示在页面的内容
    image_img.allow_tags = True  # True 显示图片 False显示html代码


class NavMenu(models.Model):
    """
    导航栏菜单
    """
    name = models.CharField(verbose_name='名称', max_length=60)

    @python_2_unicode_compatible
    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = verbose_name = '导航栏菜单'


class Category(models.Model):
    """
    分类
    """
    name = models.CharField(verbose_name='名称', max_length=100)
    nav_menu = models.ForeignKey(NavMenu, verbose_name='导航栏菜单')

    @python_2_unicode_compatible
    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = verbose_name = '分类'


class Tag(models.Model):
    """
    标签
    """
    name = models.CharField(verbose_name='名称', max_length=100)

    @python_2_unicode_compatible
    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = verbose_name = '标签'


# Create your models here.
class Post(models.Model):
    class Meta:
        '''
        News 类的内部定义一个 Meta 类，并指定排序属性：
        ordering 属性用来指定文章排序方式，['-created_time'] 指定了依据哪个属性的值进行排序，这里指定为按照文章发布时间排序，
        且负号表示逆序排列。列表中可以用多个项，比如 ordering = ['-created_time', 'title'] ，
        那么首先依据 created_time 排序，如果 created_time 相同，则再依据 title 排序。
        '''
        ordering = ['-create_time']

        # 数据库中生成的表名称 默认 app名称 + 下划线 + 类名
        # db_table = "table_name"

        # admin中显示的表名称
        verbose_name = '文章'

        # verbose_name加s
        verbose_name_plural = '文章'

    # 文章标题
    title = models.CharField(verbose_name='标题', max_length=100)
    # 根据喜好选择admin编辑器：富文本和Markdown
    is_md = models.BooleanField(verbose_name='markdown语法', default=False)
    content = models.TextField(verbose_name='内容')
    content_html = models.TextField(verbose_name='正文Html代码', blank=True, editable=False)

    # 创建时间
    create_time = models.DateField(verbose_name='创建时间', default=datetime.now)
    # 最后一次修改时间
    modified_time = models.DateField(verbose_name='修改时间')

    # 配图
    image = StdImageField(verbose_name='图片', blank=True,null=True,
                          upload_to=UploadToUUID(path='images'),  # 上传路径并使用uuid重新命名 MEDIA_ROOT/images/#UUID#.#EXT#
                          variations={'thumbnail': {"width": 200, "height": 200, "crop": True}})  # 缩略图

    # 文章摘要，可以没有文章摘要，但默认情况下 CharField 要求我们必须存入数据，否则就会报错。
    # 指定 CharField 的 blank=True 参数值后就可以允许空值了。
    excerpt = models.CharField(verbose_name='文摘', max_length=200, blank=False)

    # https://docs.djangoproject.com/en/1.10/topics/db/models/#relationships
    # 分类 根据需求 一对多关系：一篇文章对应一个分类，一个分类有多个文章
    category = models.ForeignKey(Category, verbose_name='分类')
    # 标签  根据需求 多对多关系： 一篇文章有多个标签，一个标签有多个文章
    tag = models.ManyToManyField(Tag, verbose_name='标签', blank=True, null=True)
    # 作者
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='作者')

    # 教程
    course = models.ForeignKey(Course, verbose_name='教程', blank=True, null=True)

    # 阅读量 PositiveIntegerField 类型只允许其值大于等于0
    views = models.PositiveIntegerField(verbose_name='阅读量', default=0)
    # 图片已经上传情况下，直接使用img_url
    img_url = models.URLField(verbose_name='外部图片url', blank=True, null=True)

    def url(self):
        """
        获取img_url
        :return:
        """
        if self.image:
            return self.image.url
        else:
            return ""

    def image_img(self):
        if self.image:
            href = self.image.url  # 点击后显示的放大图片
            src = self.image.thumbnail.url  # 页面显示的缩略图
            # 插入html代码
            image_html = '<a href="%s" target="_blank" title="图片下载地址"><img alt="" src="%s"/>' % (href, src)
            return image_html
        else:
            return ''

    image_img.short_description = '显示图片'  # 显示在页面的内容
    image_img.allow_tags = True  # True 显示图片  False显示html代码

    def save(self, *args, **kwargs):
        """
        将Markdown转为html
        :param args:
        :param kwargs:
        :return:
        """
        if self.is_md:
            self.content_html = mistune.markdown(self.content)
        else:
            self.content_html = self.content
        super().save(*args, **kwargs)

    def increate_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    @python_2_unicode_compatible
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.pk})

blog/forms/news.py
#!/usr/bin/evn python
# -*- coding:utf-8 -*-
# @Date    : 2019-07-10
# @Author  : suxianglun
# @Describe :
# @Version : 
from django import forms
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from blog import models


class PostAdminForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = '__all__'
        exclude = ['content_html']

    content_ck = forms.CharField(widget=CKEditorUploadingWidget(), label='正文', required=False)
    content_md = forms.CharField(widget=forms.Textarea(), label='正文', required=False)
    content = forms.CharField(widget=forms.HiddenInput(), required=False)

    def __init__(self, instance=None, initial=None, **kwargs):
        initial = initial or {}
        if instance:
            if instance.is_md:
                initial['content_md'] = instance.content
            else:
                initial['content_ck'] = instance.content

        super().__init__(instance=instance, initial=initial, **kwargs)

    def clean(self):
        is_md = self.cleaned_data.get('is_md')
        if is_md:
            content_field_name = 'content_md'
        else:
            content_field_name = 'content_ck'
        content = self.cleaned_data.get(content_field_name)
        if not content:
            self.add_error(content_field_name, '必填项！')
            return
        self.cleaned_data['content'] = content
        return super().clean()

    class Media:
        js = ('js/news_editor.js',)

blog/views.py
from django.shortcuts import render, render_to_response
from django.views import View
from django.views.generic import DetailView
from django.shortcuts import get_object_or_404

from django.utils.text import slugify

from blog.models import Post, Category, Tag, Course,NavMenu
from blog.utils.pager import PageInfo
from django.views.decorators.csrf import csrf_exempt

import mistune
import markdown
from markdown.extensions.toc import TocExtension


# Create your views here.
# class BaseView(View):
#     post_list = Post.objects.all().order_by('-id')
#     context = {'post_list': post_list}


class IndexView(View):
    def get(self, request):
        post_list = Post.objects.all().order_by('-id')
        category_list = Category.objects.all()
        tag_list = Tag.objects.all()
        course_list = Course.objects.all()
        menu_list = NavMenu.objects.all()

        context = {'post_list': post_list, 'category_list': category_list, 'tag_list': tag_list,
                   'course_list': course_list, 'menu_list': menu_list,}

        base_url = request.path_info
        all_count = Post.objects.all().count()
        page_info = PageInfo(request.GET.get('page'), all_count, 10, base_url, 11)
        context['post_list'] = post_list[page_info.start():page_info.end()]
        context['page_info'] = page_info

        return render(request, 'home.html', context=context)


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog-detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        response = super(PostDetailView, self).get(self, request, *args, **kwargs)
        self.object.increate_views()
        return response

    def get_object(self, queryset=None):
        # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
        post = super(PostDetailView, self).get_object(queryset=None)

        # convert 方法将 post.body 中的 Markdown 文本渲染成 HTML 文本
        post.body_html = mistune.markdown(post.content)
        return post

    def get_context_data(self, **kwargs):
        # 覆写 get_context_data目的不仅要将post传给模板（DetailView已经帮我们做了），还要将评论及表单传给模板
        context = super(PostDetailView, self).get_context_data(**kwargs)
        post_list = Post.objects.all().order_by('-id')
        category_list = Category.objects.all()
        tag_list = Tag.objects.all()
        course_list = Course.objects.all()
        menu_list = NavMenu.objects.all()
        context.update({
            'post_list': post_list,
            'category_list': category_list,
            'tag_list': tag_list,
            'course_list': course_list,
            'menu_list': menu_list,
        })
        return context

    def post(self, request):
        return


class CategoryView(View):

    def get(self, request, pk):
        category = get_object_or_404(Category, pk=pk)
        post_list = Post.objects.filter(category=category).order_by('-id')
        category_list = Category.objects.all()
        tag_list = Tag.objects.all()
        course_list = Course.objects.all()
        menu_list = NavMenu.objects.all()
        context = {'post_list': post_list, 'category_list': category_list, 'tag_list': tag_list,
                   'course_list': course_list,
                   'menu_list': menu_list,}
        return render(request, 'home.html', context=context)


class TagView(View):

    def get(self, request, pk):
        tag = get_object_or_404(Tag, pk=pk)
        post_list = Post.objects.filter(tag=tag).order_by('-id')
        category_list = Category.objects.all()
        tag_list = Tag.objects.all()
        course_list = Course.objects.all()
        menu_list = NavMenu.objects.all()
        context = {'post_list': post_list, 'category_list': category_list, 'tag_list': tag_list,
                   'course_list': course_list,'menu_list': menu_list,}
        return render(request, 'home.html', context=context)


class CourseListView(View):
    def get(self, request):
        post_list = Post.objects.all().order_by('-id')
        category_list = Category.objects.all()
        tag_list = Tag.objects.all()
        course_list = Course.objects.all()
        menu_list = NavMenu.objects.all()
        context = {'post_list': post_list, 'category_list': category_list, 'tag_list': tag_list,
                   'course_list': course_list,'menu_list': menu_list,}
        return render(request, 'course.html', context=context)


class CourseView(View):
    def get(self, request, pk):
        course = get_object_or_404(Course, pk=pk)
        post_list = Post.objects.filter(course=course)

        category_list = Category.objects.all()
        tag_list = Tag.objects.all()
        course_list = Course.objects.all()
        menu_list = NavMenu.objects.all()
        context = {'post_list': post_list, 'category_list': category_list, 'tag_list': tag_list,
                   'course_list': course_list,'menu_list': menu_list,}
        return render(request, 'home.html', context=context)


@csrf_exempt
def page_not_found(request):
    return render_to_response('404.html')


@csrf_exempt
def page_error(request):
    return render_to_response('500.html')

blog/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block page_body %}
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <!-- /轮播图 start-->
                <div id="myCarousel" class="carousel slide" style="padding: 0!important;">
                    <!-- 轮播（Carousel）指标 -->
                    <ol class="carousel-indicators">
                        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                        <li data-target="#myCarousel" data-slide-to="1" class=""></li>
                        <li data-target="#myCarousel" data-slide-to="2" class=""></li>
                    </ol>
                    <!-- 轮播（Carousel）项目 -->
                    <div class="carousel-inner">
                        <div class="item active">
                            <img src="{% static 'img/bg3.jpg' %}" alt="First slide">
                            <!-- 标题 -->
                            <div class="carousel-caption">不忘初心，方得始终</div>
                        </div>
                        <div class="item">
                            <img src="{% static 'img/bg2.jpg' %}" alt="Second slide">
                             <!-- 标题 -->
                            <div class="carousel-caption">静心养性，厚积薄发</div>
                        </div>
                        <div class="item">
                            <img src="{% static 'img/bg3.jpg' %}" alt="Third slide">
                             <!-- 标题 -->
                            <div class="carousel-caption">淡看一切，洒脱自如</div>
                        </div>
                    </div>
                    <!-- 轮播（Carousel）导航 -->
                    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                <!-- /轮播图 end-->
                <!-- /左侧博客列表 start-->
                <div class="left-side-blog  mt40">

                    <ul>
                        {% for rows in post_list %}
                            <li>
                                <div class="blog-pic-text mb20 " style="padding: 10px">
                                    <div class="row">
                                        <div class="col-sm-4">
                                            <div class="blog-img mt10">
                                                {% if rows.img_url %}
                                                    <img src="{{ rows.img_url }}" alt="image">
                                                {% else %}
                                                    <img src="{{ rows.url }}" alt="image">
                                                {% endif %}

                                            </div>
                                        </div>
                                        <!-- /col-md-6 -->
                                        <div class="col-sm-8 mt10">
                                            <div class="blog-text">
                                                <ul>
                                                    <li style="background: #fe533d;padding: 5px">
                                                                    <span class="tag-name "
                                                                          style="color: white">{{ rows.category }}</span>
                                                        <!-- /blog-tag -->
                                                    </li>
                                                    <li>
                                                        <a class="green" href="{% url 'blog:post_detail' pk=rows.id %}">{{ rows.title }}</a>
{#                                                        <a class="green" href="{{ rows.get_absolute_url }}">{{ rows.title }}</a>#}
                                                        <!-- /blog-tag -->
                                                    </li>
                                                </ul>


                                                <div class="blog-text-content mt10 ">
                                                    <p>
                                                        {{ rows.excerpt }}
                                                    </p>
                                                </div>
                                                <div class="blog-meta mt10 pb10">
                                                    <ul class="meta-list">
                                                        <li><a class="green" href="#"><span
                                                                class="mr5 ti-pencil"></span> {{ rows.author }}
                                                        </a></li>
                                                        <li><a href="#"><span class="mr5 ti-timer"></span>
                                                            {{ rows.create_time }}</a></li>
                                                        <li><a href="#"><span
                                                                class="mr5 ti-comment-alt"></span>0</a>
                                                        </li>
                                                        <li><a class="red" href="#"><span
                                                                class="mr5 ti-heart"></span>0</a>
                                                        <li><a href="#"><span
                                                                class="mr5 ti-layout-media-overlay"></span>{{ rows.views }}
                                                        </a>
                                                        </li>
                                                    </ul>
                                                </div>

                                            </div>
                                            <!-- /blog-text -->
                                        </div>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}

                    </ul>
                    <nav class="text-center" aria-label="Page navigation">
                        <ul class="pagination">
                            {{ page_info.pager|safe }}
                        </ul>
                    </nav>
                    <!-- /blog-text-pic -->

                </div>

                <!-- /左侧博客列表 end-->
            </div>

        </div>


    </div>




{% endblock %}

blog/templates/navbar.html
<!-- 整个菜单栏部分  悬浮在最上层 -->
{% load static %}
{% load tags %}
<header>
    <div class="header-top-bg">
        <div class="container">
            <div class="row">
                <div class="header-top">
                    <div class="head-top-info pull-left">
                        <ul class="top-info">
                            <li style="color: #fe533d"><img style="height: 10%!important;"
                                                            src="{% static 'img/logo-24.png' %}" alt="image">用脚步去丈量梦想的距离
                            </li>
                        </ul>
                    </div>
                    <!-- /head-top-info -->
                    <div class="header-social pull-right">
                        <div class="social">
                            <ul class="social-list">
                                <li><a href="#"><span class="ti-github"></span></a></li>
                                <li><a href="#"><span class="ti-google"></span></a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- /header-social -->
                </div><!-- /header-top -->
            </div><!-- /row -->
        </div><!-- /container -->
    </div>
    <div class="menu-bar  mb20">
        <div class="container">
            <div class="row">

                <!-- 导航栏 -->
                <nav class="navbar">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <!-- 适配手机展示的导航栏 -->
                    <div class="navbar-header">
                        <a class="navbar-brand" style="color: #fe533d" href="{% url 'blog:home' %}">博客</a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <!-- 导航栏菜单部分 -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="{% url 'blog:home' %}">首页 </a></li>
                            <li><a href="{% url 'blog:course_list' %}">教程</a>
                                <ul class="menu-dropdown">
                                    {% for foo in course_list %}
                                        <li><a class="text-center"
                                               href="{% url 'blog:course' foo.id %}">{{ foo.name }}</a></li>
                                    {% endfor %}

                                </ul>
                            </li>
                            {% for foo in menu_list %}
                                <li><a>{{ foo.name }}</a>
                                    <ul class="menu-dropdown">
                                        {% get_category_from_menu foo.name as categorys %}
                                        {% for foo1 in categorys %}
                                            <li><a href="{% url 'blog:category' foo1.id %}">{{ foo1.name }}</a></li>

                                        {% endfor %}

                                    </ul>
                                </li>
                            {% endfor %}
                            <li><a>关于</a>
                                <ul class="menu-dropdown">
                                    <li><a href="404.html">关于博客</a></li>
                                </ul>
                            </li>
                        </ul>

                    </div>


                </nav>


                <div class="wrap">
                    <!--MENU-->
                    <div id="main-menu">
                        <div class="menu-btn">
                            <div class="menu-btn-line menu-btn-line-1"></div>
                            <div class="menu-btn-line menu-btn-line-2"></div>
                            <div class="menu-btn-line menu-btn-line-3"></div>
                        </div>

                        <nav class="navbar ownavigation">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle" data-toggle="collapse"
                                        data-target="#navbar" aria-expanded="true" aria-controls="navbar">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                            </div>
                            <div id="navbar" class="navbar-collapse collapse navbar-right collapse in"
                                 aria-expanded="true">
                                <ul class="nav navbar-nav">
                                    <li><a href="{% url 'blog:home' %}" title="About Us">首页</a></li>
                                    <li class="dropdown">
                                        <a class="dropdown-toggle" title="Pages"
                                           data-toggle="dropdown"
                                           role="button" aria-haspopup="true" aria-expanded="false"
                                           href="{% url 'blog:course_list' %}">教程</a>
                                        <ul class="dropdown-menu ">
                                            {% for foo in course_list %}
                                                <li><a class="text-center"
                                                       href="{% url 'blog:course' foo.id %}">{{ foo.name }}</a></li>
                                            {% endfor %}

                                        </ul>
                                    </li>

                                    <li class="dropdown">
                                        <a class="dropdown-toggle" title="Pages"
                                           data-toggle="dropdown"
                                           role="button" aria-haspopup="true" aria-expanded="false">技术</a>
                                        <ul class="dropdown-menu">
                                            <li><a class="text-center" href="">Python</a></li>
                                            <li><a class="text-center" href="">Java</a></li>
                                            <li><a class="text-center" href="">Android</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown">
                                        <a class="dropdown-toggle" title="Pages"
                                           data-toggle="dropdown"
                                           role="button" aria-haspopup="true" aria-expanded="false">管理</a>
                                        <ul class="dropdown-menu">
                                            {#                                        <li><a href="{% url 'document' %}">Navi++文档</a></li>#}
                                            {#                                        <li><a href="{% url 'document' %}">软件下载</a></li>#}
                                            <li><a class="text-center" href="">项目管理</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown">
                                        <a class="dropdown-toggle" title="Pages"
                                           data-toggle="dropdown"
                                           role="button" aria-haspopup="true" aria-expanded="false">生活</a>
                                        <ul class="dropdown-menu">
                                            {#                                        <li><a href="{% url 'document' %}">Navi++文档</a></li>#}
                                            {#                                        <li><a href="{% url 'document' %}">软件下载</a></li>#}
                                            <li><a class="text-center" href="">感悟</a></li>
                                            <li><a class="text-center" href="">沉思</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown">
                                        <a class="dropdown-toggle" title="Pages"
                                           data-toggle="dropdown"
                                           role="button" aria-haspopup="true" aria-expanded="false">关于</a>
                                        <ul class="dropdown-menu">
                                            {#                                        {% for foo in news_category_list %}#}
                                            {#                                            <li><a href="{% url 'news_list' foo.id %}">{{ foo.name }}</a></li>#}
                                            {#                                        {% endfor %}#}
                                            <li><a class="text-center" href="404.html">关于博客</a></li>
                                        </ul>
                                    </li>

                                </ul>

                            </div>
                        </nav><!-- Ownavigation /- -->

                    </div>
                    <!-- END menu -->
                </div><!--/wrap  -->
            </div><!--/row  -->
        </div><!--/container  -->
    </div><!--/menu-bar  -->
</header>